language: ruby
bundler_args: --without production
services:
  - postgresql

before_script:
  - rails db:create
  - rails db:migrate

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

script:
  - rails test
  - rails webpacker:compile

