language: ruby
bundler_args: --without production
services:
  - postgresql

before_script:
  - rails db:create
  - rails db:migrate
  - RAILS_ENV=test bundle exec rails webpacker:compile
script:
  - rails test

